# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_category_test <- function(input, output, cutoff, root, silent) {
    invisible(.Call('ABAEnrichment_hyper_category_test', PACKAGE = 'ABAEnrichment', input, output, cutoff, root, silent))
}

hyper_randset <- function(all_genes, number_of_randomsets, directory, root, mod, silent) {
    invisible(.Call('ABAEnrichment_hyper_randset', PACKAGE = 'ABAEnrichment', all_genes, number_of_randomsets, directory, root, mod, silent))
}

unlock_environment <- function(env) {
    .Call('ABAEnrichment_unlock_environment', PACKAGE = 'ABAEnrichment', env)
}

wilcox_category_test <- function(input, output, cut, root, silent) {
    invisible(.Call('ABAEnrichment_wilcox_category_test', PACKAGE = 'ABAEnrichment', input, output, cut, root, silent))
}

wilcox_randset <- function(nodes_per_gene, number_of_randomsets, directory, root, silent) {
    invisible(.Call('ABAEnrichment_wilcox_randset', PACKAGE = 'ABAEnrichment', nodes_per_gene, number_of_randomsets, directory, root, silent))
}

