# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_category_test <- function(input, output, cutoff, root) {
    invisible(.Call('ABAEnrichment_hyper_category_test', PACKAGE = 'ABAEnrichment', input, output, cutoff, root))
}

hyper_randset <- function(detected, number_of_randomsets, directory, root, mod) {
    invisible(.Call('ABAEnrichment_hyper_randset', PACKAGE = 'ABAEnrichment', detected, number_of_randomsets, directory, root, mod))
}

unlock_environment <- function(env) {
    .Call('ABAEnrichment_unlock_environment', PACKAGE = 'ABAEnrichment', env)
}

wilcox_category_test <- function(input, output, cut, root) {
    invisible(.Call('ABAEnrichment_wilcox_category_test', PACKAGE = 'ABAEnrichment', input, output, cut, root))
}

wilcox_randset <- function(nodes_per_gene, number_of_randomsets, directory, root) {
    invisible(.Call('ABAEnrichment_wilcox_randset', PACKAGE = 'ABAEnrichment', nodes_per_gene, number_of_randomsets, directory, root))
}

